---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  CPAN::Meta: 0
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.14'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EzyApp-Store-Mango
no_index:
  directory:
    - inc
    - t
version: undef
